### ISSUE TITLE
Nvim-bspconfig ?

### ISSUE THREAD

**Issue by LamprosPitsillos** [616b2f/bsp.nvim#3]
Since this is definitely something new, it would be nice if something like `nvim-lspconfig` existed but for bsp's. Im not suggesting that you maintain such a repo, just that some examples are provided , for people to copy and create their own or something similar.

A small example in the readme for setting up let's say FOO BSP would be nice , thank you for your hard work, hope to see this up stream at some point!

**Comment by 616b2f** [comment]
Hi, thank you for your interest. I actually have a small section in the README for how to create the configuration. It's little bit different then for LSP servers, because by the specification it's created as a JSON file in the root of your project or in a well-known location for the user or system wide.

If you are interested in the details, you can read them up here https://build-server-protocol.github.io/docs/overview/server-discovery#default-locations-for-bsp-connection-files 

Currently this plugin only supports configuration files that are located in the project root, as it was the simplest case to implement. In the future I would like to create also system wide configurations and provide a way how you can configure when the server should be started.
